//Initialisation des paramètres du jeu
var guessForm = $(".guessForm");
var guessLetter = $(".guessLetter");
var guessWord = $(".guessWord");
var words = ["africa","snake","canyon","truck","hangman","website","clock","wagon","palmtree","headphone","donkey","pancake","amazing","wonderful","handkerchief","thief","banana"];
var word = words[Math.floor(Math.random() * words.length)];
var remainingLetters = word.length;
var wrongLetters = $(".wrongLetters");
var wrongArray = [];
console.log(word);
this.setup();

//Affichage de la progression
var answerArray = [];
for (var i = 0; i < word.length; i++) {
	answerArray[i] = "_";
}
this.guessWord.text(answerArray.join(" "));

function setup () {
	this.guessForm.on("submit", $.proxy(this.checkLetter, this));
}

function checkLetter (form) {
	form.preventDefault();
	var letter = this.guessLetter.val();
	if (letter.length == 1) {
		if (word.includes(letter)) {
			for (var i = 0; i < word.length; i++) {
				if (word[i] == letter) {
					answerArray[i] = letter;
					this.guessWord.text(answerArray.join(" "));
					remainingLetters--;
				}
			};
			console.log(remainingLetters);
			if (remainingLetters == 0) {
				alert("CONGRATS! You've won!");
			}
		} else {
			wrongArray.push(letter);
			this.wrongLetters.text(wrongArray.join(" "));
		}
	}
	this.guessLetter.val("").focus();
}

/*

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec erat metus, accumsan in tincidunt sit amet, condimentum vel mi. Pellentesque imperdiet felis et dolor convallis ultricies. Vivamus ut ullamcorper nunc. Curabitur tristique nibh et ante dignissim, ut posuere lectus pretium. Curabitur interdum nisi enim, aliquam pharetra dolor semper quis. Nunc mi nisl, lobortis et nulla ut, posuere scelerisque nisi. Donec eu tempus libero, sit amet scelerisque arcu. Nulla cursus quam nec neque efficitur finibus in ut augue. Curabitur non diam vel est vulputate pulvinar. Quisque vehicula sapien nec odio luctus pharetra. Nam quis semper tellus.

Morbi sed porttitor tortor. Curabitur gravida fringilla justo, quis aliquam nisl condimentum et. Ut et nisi quis nisl commodo viverra. Nunc id erat at ligula ullamcorper mollis vitae at tortor. Praesent in dolor ac erat consequat tincidunt. Vivamus tincidunt, mauris a consectetur consectetur, lectus nisl cursus libero, non molestie nunc mauris a ipsum. Etiam sagittis nunc nisl, eget sodales massa congue sit amet.

Vestibulum quis turpis sem. Pellentesque in felis sit amet erat condimentum interdum at non elit. Quisque porttitor blandit suscipit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin at metus ligula. Aenean at semper erat, eu bibendum metus. Etiam facilisis, arcu sed dictum vehicula, tortor sem euismod odio, sit amet pretium augue nulla ut lacus. Phasellus placerat iaculis nisi, at venenatis justo accumsan ut. Proin tempus cursus enim, vel consequat elit malesuada ut. Duis sed cursus quam. Quisque viverra facilisis velit, eleifend hendrerit neque placerat id. Curabitur tortor est, placerat nec ultrices luctus, consequat a mauris. Praesent et nibh vitae felis suscipit scelerisque. Sed in sapien non ipsum eleifend scelerisque. Fusce pulvinar augue at magna mattis, ac ultrices nisl euismod.

Etiam lobortis ut quam at dictum. Pellentesque in nisl eu tortor maximus viverra et sed nibh. Fusce ut velit erat. Praesent et iaculis magna, et facilisis lorem. Cras elementum dui turpis, a pellentesque massa volutpat ac. Cras aliquet enim sit amet lacus rhoncus ullamcorper. Curabitur imperdiet orci congue sem consequat fringilla. Duis et massa vel diam consequat convallis a id urna. Aliquam erat volutpat. Quisque congue aliquet ullamcorper. Praesent pellentesque justo id commodo hendrerit.

Fusce aliquam et neque sit amet suscipit. Nunc risus nisl, ornare sed enim ut, ornare ullamcorper eros. Nulla facilisi. In a ligula urna. Nullam at tortor condimentum nibh commodo elementum vel ut turpis. In vel venenatis ex, et hendrerit sapien. Donec ipsum elit, ornare ac commodo at, aliquam vitae velit. Duis non dignissim erat. Fusce vestibulum rutrum nisi vel hendrerit. Morbi vel mauris efficitur, tristique erat id, eleifend dui. Cras id pharetra elit, nec ultricies metus. Ut ac ipsum eu mi rhoncus bibendum. Aenean pretium diam mollis, aliquet enim nec, tempus quam.

Quisque vulputate ipsum diam, et mattis nunc pretium ullamcorper. Duis hendrerit lorem in mauris convallis, in cursus ex sollicitudin. Mauris non erat vitae tortor eleifend pretium. Aenean condimentum volutpat est, nec aliquet tortor ornare non. Fusce maximus sem vel purus congue, sit amet posuere nunc fringilla. Integer feugiat massa id mauris suscipit lobortis. Nulla placerat ut risus vel dapibus. Aliquam vitae leo iaculis, sodales justo vel, ornare urna. Aliquam nisl erat, feugiat non erat ut, vestibulum fermentum ipsum. Curabitur eget arcu diam. Ut at nulla ut arcu congue aliquet nec nec nulla. Donec tempor purus ex, vel lacinia tellus porta eu. Cras imperdiet tempor tincidunt. Morbi sodales, nunc non aliquam ultrices, orci sem interdum velit, quis egestas orci enim eu diam. Morbi ultrices ex tellus, nec tincidunt magna ornare ac. Vestibulum aliquam vitae quam sed pellentesque.

Duis eget enim nec est condimentum hendrerit. Etiam mi mi, egestas vel congue eu, molestie eget ipsum. Nullam sed libero vitae risus sodales elementum vitae ac odio. Maecenas non magna mollis, mattis est tempor, rutrum libero. Integer finibus est odio, ut laoreet dui facilisis in. Quisque nec sem non lorem faucibus molestie. Maecenas ac purus imperdiet, molestie orci volutpat, ultrices sapien. Nunc ultrices vulputate velit. In tempor eleifend aliquet. Sed imperdiet nisi rutrum ex varius, ut finibus lectus tempus. Aliquam feugiat magna nec ultricies tristique. Vivamus sit amet vehicula massa, vitae posuere velit. Aenean libero erat, hendrerit sit amet varius eu, aliquam vel purus. Ut sed quam faucibus, tempor lorem scelerisque, sodales arcu. Mauris id ullamcorper mauris.

Suspendisse in cursus odio. Quisque erat ex, tempus id orci at, facilisis lacinia sem. Nulla eu mollis mi. Morbi non cursus eros. Vestibulum purus sem, viverra eu fermentum quis, pharetra non magna. Fusce ut dapibus nisl, id consectetur est. Donec ullamcorper vulputate pellentesque.

Sed ligula augue, convallis congue nulla eu, blandit imperdiet erat. Sed gravida efficitur felis et sollicitudin. Fusce laoreet nunc condimentum libero dictum, quis interdum libero varius. Vestibulum tincidunt urna nec laoreet tincidunt. In at mauris at nunc ultrices molestie. Aenean egestas ante ut risus aliquet rhoncus. Vestibulum non justo nec massa varius fermentum. Aenean vitae malesuada tortor. Curabitur at suscipit lectus, ac posuere risus.

Nam at mattis libero. Fusce non nisi venenatis, fringilla quam id, malesuada arcu. Vestibulum eget tincidunt nunc, in feugiat felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas eu dolor vel purus tincidunt ultricies. Aliquam odio nulla, condimentum sit amet odio sit amet, pellentesque dapibus quam. Maecenas eget sem eros. Integer pellentesque orci vitae justo luctus, fermentum mollis lorem vehicula. Donec hendrerit feugiat convallis. In ultrices quis arcu in ultricies. Donec quis pretium turpis. Mauris placerat nulla quis nulla molestie, id fringilla erat tempus.

Cras a rhoncus ex. Cras id libero enim. Quisque vulputate magna non faucibus posuere. Nulla faucibus, orci pellentesque fermentum commodo, nisl enim maximus augue, sit amet pulvinar elit augue convallis lorem. Integer purus enim, convallis eu egestas eget, porta imperdiet nisl. Sed varius lectus augue, at volutpat felis tincidunt ut. Praesent aliquet auctor feugiat. Cras nisl massa, finibus a fringilla vel, iaculis non ex.

Vestibulum at sem hendrerit, dapibus nunc vel, auctor turpis. Vestibulum tempor porta enim, sit amet volutpat urna pulvinar id. Praesent elit mi, tempus vel nisl nec, convallis commodo odio. Etiam sit amet lorem a velit vestibulum laoreet. Nunc a laoreet ipsum, at aliquet tellus. Pellentesque imperdiet blandit pellentesque. Proin a elit gravida, lobortis quam quis, maximus nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ornare mollis ultricies. Morbi iaculis maximus facilisis. In hac habitasse platea dictumst. Etiam efficitur rhoncus nibh id blandit. Curabitur in tortor et odio lacinia sodales hendrerit ac nulla. Aliquam sit amet sem lectus.

Donec eu tempor tellus. Duis laoreet sed lacus et pellentesque. Nulla id sodales nisi, in mollis enim. Fusce sed orci velit. Sed lobortis aliquam scelerisque. Aliquam fermentum, quam et dapibus vulputate, libero quam molestie ante, finibus hendrerit augue mi vel ipsum. Vestibulum commodo, justo at convallis dapibus, enim metus eleifend enim, vitae consequat libero magna sit amet mauris. Suspendisse a ligula dictum, rutrum libero in, convallis ipsum. Curabitur id hendrerit purus. Cras est sem, suscipit fermentum magna commodo, scelerisque vulputate neque. In hac habitasse platea dictumst. Praesent cursus mattis ipsum sed tincidunt. Nulla eu lorem posuere, laoreet lectus at, euismod odio. Praesent lacinia sit amet enim at varius.

Cras vitae dui gravida, ornare turpis vel, pulvinar sem. Morbi justo ipsum, finibus in arcu quis, lobortis rutrum elit. Nulla non posuere elit, quis fermentum dolor. In vel justo ac purus bibendum aliquam ut vel ex. Sed venenatis dignissim urna, quis vehicula augue ultrices nec. Aenean vitae turpis eu sem laoreet consectetur. Proin cursus dolor sit amet lectus gravida tempor. Fusce sit amet justo luctus, luctus nisl pulvinar, aliquam magna. Etiam nec nunc aliquam, venenatis nunc dictum, imperdiet ex. Phasellus ornare erat eros, nec elementum elit consectetur id. Aenean nec laoreet metus. Cras ac suscipit enim. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Quisque ut facilisis felis. Donec dignissim varius lacus, a faucibus diam vulputate non. Donec sagittis dolor congue aliquet tristique. Vestibulum vitae lacus felis. Nullam consectetur justo felis, nec ullamcorper quam iaculis a. Nulla porta eros elit, at imperdiet sem tincidunt venenatis. Ut sagittis interdum arcu quis euismod. Mauris non neque nec tortor egestas finibus. In sit amet lobortis nibh, sed iaculis ante. Etiam in nisl et ipsum consectetur tempor nec interdum lectus. Integer in scelerisque magna, in efficitur urna. Phasellus sit amet venenatis tortor. In ac eros quis dolor cursus commodo.

Maecenas lacinia elit nisi, a vulputate justo feugiat quis. Vivamus sed mollis turpis, sed maximus urna. Vivamus pretium hendrerit justo, non luctus lacus. Maecenas aliquam nunc id enim ullamcorper, sit amet pharetra odio ultricies. Duis non lectus quis risus gravida blandit. Integer non mi quis erat vulputate viverra non eget ipsum. Nullam urna dolor, fermentum non ultricies id, scelerisque sit amet arcu. Mauris diam ipsum, accumsan eu iaculis et, bibendum gravida diam. Phasellus sagittis molestie cursus. Proin porttitor blandit est, ut hendrerit ex posuere sit amet. Integer felis enim, consectetur dignissim dui nec, finibus commodo ligula. Praesent eget dui pretium, dapibus eros nec, imperdiet leo. Nunc ut porta velit, a faucibus lectus. Quisque suscipit dictum nunc non ultrices. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi sit amet semper lorem.

Aenean eget commodo nulla. Nullam sit amet metus tincidunt arcu dictum fermentum. Cras sed nulla nunc. Fusce egestas porttitor luctus. Sed et libero eget nisl suscipit luctus vel gravida quam. Nam iaculis id nulla a dapibus. Nunc efficitur risus vel feugiat pretium.

Aliquam ut justo lorem. Nullam vehicula quam risus, in vulputate sem tempor ac. Donec rhoncus ipsum nibh, at dignissim mauris tincidunt et. In auctor dolor a nisi aliquet, ac mattis diam lobortis. Ut convallis lorem ac sagittis rhoncus. Curabitur bibendum est eget eros porttitor, vel pellentesque purus mattis. Vivamus congue venenatis tellus, varius scelerisque nisi facilisis iaculis. Vivamus dapibus massa faucibus magna feugiat, quis fermentum magna semper.

Pellentesque ornare a sem accumsan placerat. Mauris varius libero arcu, vitae porttitor orci iaculis eget. Proin accumsan venenatis ipsum suscipit hendrerit. Proin viverra enim neque, nec volutpat ligula fringilla eu. Praesent sollicitudin lorem quis lacus aliquam suscipit. Nunc efficitur tempor enim et elementum. Donec consequat dapibus odio a pharetra. Vivamus non volutpat magna. Aliquam luctus eget est nec imperdiet. Proin interdum porttitor purus vitae accumsan.

Aliquam et iaculis justo, sit amet dignissim ipsum. Duis viverra ligula enim, non dictum leo faucibus id. Sed eget venenatis est. Mauris sollicitudin ex sem, sed vestibulum diam ultrices et. Phasellus laoreet ligula non purus tincidunt eleifend quis eget velit. Sed faucibus interdum nisi nec consectetur. Aliquam erat volutpat. Integer vel lacinia risus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Donec volutpat, erat et luctus viverra, velit nisl interdum quam, vitae laoreet dolor mi sed dolor. Sed sit amet metus nibh. Aenean ac enim et nunc volutpat pretium ut finibus diam. In nec gravida quam. Vivamus dignissim leo felis. Suspendisse nec tempor massa. Donec non orci orci. Phasellus vitae lorem nec urna elementum consequat rhoncus ac lectus. Phasellus vitae elit sed augue lobortis varius facilisis a mauris. Vivamus congue placerat vulputate. Proin eget sapien et lectus euismod pharetra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque non cursus lectus.

Morbi venenatis sapien elit, at lacinia metus ornare in. Curabitur viverra justo vel nisl aliquam, nec semper quam bibendum. Nulla id pharetra nisi, non efficitur diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer ac leo nibh. Fusce mi nibh, laoreet non urna a, venenatis feugiat risus. Suspendisse potenti. Suspendisse potenti. Vivamus efficitur eu ex varius finibus.

Fusce molestie tellus tellus, sit amet porttitor nulla vestibulum quis. Nulla et ex aliquam, porttitor turpis scelerisque, dignissim elit. Donec pharetra turpis odio, id fermentum erat vestibulum in. Fusce vitae fringilla sem. Ut sit amet ex blandit lectus pulvinar scelerisque non ut dolor. Quisque pulvinar sollicitudin arcu sed finibus. Etiam egestas molestie bibendum. Curabitur tempor sit amet justo in laoreet. Nulla laoreet dolor ut purus hendrerit, eu eleifend lorem dictum. Vestibulum sed nisi convallis, sollicitudin erat quis, euismod velit. Vivamus id dolor ac nisl tincidunt feugiat. Suspendisse potenti. Donec ut risus non justo mattis bibendum vitae at purus. Maecenas vehicula ac arcu ut dictum.

Nullam sed ex est. Donec sodales, tellus sed vestibulum volutpat, velit nibh maximus ante, ut viverra tellus erat sit amet augue. Suspendisse potenti. Nullam ac bibendum leo. Aenean facilisis, metus id condimentum gravida, justo nisl rutrum massa, id facilisis mauris dui eu leo. Donec euismod rutrum eros. In aliquam arcu ac mauris consectetur, sit amet venenatis nisi imperdiet. Proin auctor faucibus consequat. Etiam facilisis tellus scelerisque justo faucibus interdum. Aenean sed nibh eu ligula posuere pharetra. Phasellus tincidunt pharetra mauris, eu vulputate purus pulvinar vel. Praesent vulputate justo eleifend, porta quam ac, sodales tellus. Proin efficitur nisl urna, nec varius metus interdum quis. Morbi in semper ex.

Nullam volutpat tortor vitae augue vestibulum aliquam. Morbi sit amet sapien sed risus vulputate vehicula. Nunc eu neque viverra, iaculis ipsum vel, tincidunt libero. Sed sollicitudin eu velit ut pulvinar. Cras tellus nisl, semper tempus convallis id, feugiat vitae est. Integer neque justo, varius vulputate lorem id, euismod lacinia leo. Morbi eu erat massa. Morbi dictum elementum facilisis. Praesent a consequat massa, quis commodo justo. Nullam pretium vel metus nec elementum.

Fusce at eleifend sem. Curabitur quis cursus libero. Praesent nulla quam, laoreet vehicula nulla ut, iaculis finibus sapien. Etiam id volutpat urna, at facilisis urna. Suspendisse faucibus enim a molestie pharetra. In hac habitasse platea dictumst. Sed mi neque, tincidunt vel pulvinar ac, sagittis at turpis. Nulla facilisi.

Maecenas justo dolor, tincidunt a venenatis non, malesuada sed turpis. Vivamus eleifend elit et bibendum congue. Curabitur mollis vel felis non consectetur. Integer facilisis orci tellus, vitae posuere nisl ullamcorper vitae. Aliquam erat volutpat. Pellentesque maximus justo nec leo dapibus bibendum. Duis ut aliquet nisl, vitae pulvinar sem. Nullam venenatis ante in tellus eleifend, id maximus metus interdum. Cras at venenatis erat. Vestibulum hendrerit porttitor ligula non ultrices. Sed ac orci non ligula interdum egestas. Aliquam et finibus felis, quis pulvinar eros. Nullam ultricies tempor sem, ut pharetra dui efficitur ac. Aenean faucibus porta sem.

Morbi egestas, tortor nec facilisis semper, quam sapien pulvinar diam, at accumsan leo quam vitae orci. Praesent vel sodales arcu. Donec consequat nec ex nec ultrices. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed eget tortor lacus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed urna lacus, interdum sit amet sollicitudin non, tempus nec augue. Sed sit amet rutrum lacus. Aliquam finibus lorem ut felis pulvinar, a auctor ipsum sodales. Quisque erat sem, rhoncus sit amet euismod vitae, vestibulum a nisi. Cras aliquet, ex non dapibus tristique, nisl quam molestie ipsum, et elementum purus sem ut velit. Nam feugiat neque lorem, ut pharetra tellus eleifend non.

Nam ultricies blandit quam a feugiat. Etiam porta nec leo ut mattis. Aenean in porta ex. Sed scelerisque ex id lectus placerat, a gravida tellus viverra. Phasellus at consequat odio. Nullam ante turpis, condimentum a eros vel, tincidunt tincidunt velit. Duis condimentum sit amet felis nec tempor. Fusce non pretium velit. Pellentesque efficitur, nibh sed vehicula elementum, enim magna dignissim velit, vitae dignissim est quam quis augue.

Sed ut ipsum a quam consequat tempus vitae nec diam. Donec in risus libero. In consectetur porttitor magna ut semper. Suspendisse nec felis a ante tincidunt mollis. Morbi eget ipsum eu arcu vestibulum imperdiet vel nec ligula. Pellentesque malesuada magna ut congue auctor. Aenean quis fringilla augue, eu egestas libero. Fusce eget laoreet elit, non lobortis justo. Duis in nisi elementum, feugiat dolor vitae, porttitor diam. Nam elit mi, venenatis non turpis vel, imperdiet laoreet tortor. Vivamus egestas nisl at arcu varius, sit amet porttitor est aliquam.

Ut volutpat, orci nec dignissim malesuada, risus erat luctus tellus, commodo iaculis elit nunc imperdiet nulla. Nunc libero justo, pretium at metus sit amet, tristique lobortis eros. Aliquam non purus eu orci vestibulum vestibulum sit amet nec turpis. Aliquam eu lectus porta, accumsan felis ultricies, egestas tortor. Integer aliquet et augue id commodo. Sed mollis mattis lacus, sit amet varius erat lobortis quis. Nullam non enim libero. Maecenas interdum id lacus id posuere. Sed semper augue in accumsan feugiat. Nunc sit amet luctus dolor. Mauris rhoncus ac elit tincidunt pretium. Integer accumsan sodales lacinia. In hac habitasse platea dictumst. Pellentesque ac enim sed ante blandit luctus et id lacus. Etiam blandit hendrerit elit.

Cras sed lacus at est iaculis laoreet eget eget neque. Ut laoreet erat dapibus, semper justo sed, aliquet quam. Etiam a ullamcorper odio. Suspendisse non purus tempor, laoreet turpis hendrerit, auctor diam. Ut pharetra, lacus et venenatis tristique, tellus nibh fringilla nisl, quis tincidunt augue justo id dui. Donec posuere at turpis sed vulputate. Nam convallis rhoncus odio, ut euismod ipsum ullamcorper in. Quisque ac vulputate mi, nec tempus ligula. Mauris ac lectus et urna mattis maximus.

Mauris varius posuere ipsum eu eleifend. Nulla rutrum sollicitudin nulla quis molestie. Ut mollis magna in purus tristique, a porttitor diam imperdiet. Vestibulum sodales eu ligula quis pellentesque. Vivamus accumsan lorem nec urna efficitur, non semper ante varius. Vivamus quis odio nisl. Proin ipsum eros, hendrerit eget mauris vitae, sodales blandit ligula. Vestibulum sed tortor et lectus viverra efficitur nec vel sapien.

In commodo libero eget auctor aliquet. Phasellus feugiat lacinia tempus. Fusce ornare arcu massa, non tempor nisl placerat at. Quisque et consequat dolor. Fusce ultrices porttitor volutpat. Curabitur eget dictum tortor. Vivamus eleifend nisl erat, quis sodales lacus vehicula ut. Duis in leo eu nulla sagittis tempus. Proin pretium id felis eu suscipit. Sed et velit vestibulum, sagittis justo nec, tincidunt justo. Mauris id varius tortor.

Praesent luctus elit a enim cursus, non laoreet felis tristique. In id purus vitae dui laoreet sollicitudin ut sit amet diam. Vestibulum sollicitudin turpis a magna accumsan mattis. Praesent a congue sem, a aliquam massa. Nunc semper est sollicitudin magna rutrum, eget pretium est luctus. Donec eu elit felis. Phasellus venenatis, eros at ultrices laoreet, justo enim tempus eros, non tincidunt urna risus mollis nisl. Vivamus ut nisl vehicula, pulvinar nisl pharetra, finibus libero. Vivamus dapibus aliquet tortor, eu bibendum nisl tristique eget. Nullam vulputate quam convallis justo pulvinar, at dapibus est mollis. Aliquam erat volutpat. Sed feugiat sollicitudin suscipit. Duis volutpat rhoncus lorem, ac gravida leo sollicitudin at.

In faucibus nisi sed erat lacinia, id ullamcorper quam fermentum. Etiam tincidunt ac lectus vel laoreet. In cursus dictum lacus, eget sollicitudin purus tincidunt ut. Cras consectetur magna sit amet gravida feugiat. Vivamus consequat tortor ac odio commodo laoreet. Donec in semper tellus, eu lacinia lectus. Duis gravida porttitor neque, nec vestibulum mi. Pellentesque vel aliquet ex, quis tristique neque. Nulla vitae fermentum diam, ac rutrum metus. Quisque bibendum ultricies augue id fringilla. Sed ornare erat eget enim ultricies, consectetur aliquet leo iaculis. Morbi nulla erat, tempus quis fermentum ut, maximus sit amet nunc.

Sed id urna eget risus eleifend varius a vitae massa. Curabitur mollis eu nibh ac convallis. Morbi dignissim, libero nec porttitor facilisis, purus ipsum posuere leo, sed rhoncus risus leo id risus. Praesent rutrum sed justo et bibendum. Donec a tempus leo. Quisque et elit nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla facilisi. Nulla id erat ornare felis tempor placerat. Ut rutrum, arcu sed interdum porttitor, nibh est blandit nibh, quis cursus tortor enim sit amet turpis. Sed lacus risus, lobortis quis libero quis, consectetur condimentum ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras consectetur mollis elit eu fermentum. Duis magna quam, semper eu tortor in, volutpat cursus risus.

Vestibulum ac lacus tellus. Suspendisse facilisis, dui in tempus pharetra, risus arcu posuere odio, vel aliquam elit ex eu eros. Maecenas convallis nulla sed pharetra porttitor. Maecenas vel mauris neque. Curabitur ornare tortor velit, eu ultricies nisl faucibus pretium. Praesent dui est, condimentum at ullamcorper sit amet, sodales et orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed a leo laoreet, sollicitudin augue quis, varius tortor. Ut efficitur commodo tempor. Cras eleifend auctor dui, et venenatis lectus tempus eget. Proin auctor diam tellus, euismod congue neque molestie at. Maecenas imperdiet, nulla quis lacinia sagittis, orci diam scelerisque arcu, in posuere tellus est in sem. Praesent varius quis erat et molestie. Suspendisse facilisis, tortor ut porta pulvinar, sem erat tempus nisl, in convallis tortor nisl vel odio. Nulla a nunc et dui eleifend egestas. Curabitur vel eros sit amet sem fringilla luctus in in lacus.

Quisque pulvinar nibh eu leo molestie consequat. Integer quam ante, porttitor at elit id, mattis sollicitudin dolor. Aenean tincidunt laoreet velit a ultricies. Nulla lobortis imperdiet dolor sit amet accumsan. Vivamus at aliquam tortor, sit amet pulvinar odio. Quisque porta nibh ut tortor blandit tincidunt. Pellentesque eget ornare eros. Pellentesque porttitor justo eu sapien sagittis, eu suscipit lorem ultricies. Pellentesque elit tortor, faucibus eu fringilla sed, euismod ornare est. Etiam imperdiet consectetur dolor nec feugiat. Vivamus ultrices accumsan nibh id elementum. Nullam ut sodales tellus. Maecenas elementum sit amet dolor vitae porttitor. Aenean id sagittis nisi.

Etiam vitae elementum sem. Praesent et efficitur massa, vel maximus nisl. Pellentesque vulputate diam quis fringilla rhoncus. Curabitur mattis, lacus a facilisis commodo, libero lorem mattis ligula, in cursus dui risus vel lacus. Quisque eget nibh nec magna scelerisque sagittis. Praesent dapibus lacus ut ex viverra faucibus. Proin gravida eget lorem a efficitur. Vestibulum sed justo auctor, rhoncus elit vitae, imperdiet eros. Donec non leo feugiat, commodo nisl quis, suscipit magna. Phasellus nec orci sed justo laoreet consequat sagittis eu justo. Sed a finibus sem. Ut rhoncus elementum neque sit amet scelerisque. Pellentesque mollis aliquet rhoncus. Aliquam massa ante, aliquet in lorem et, faucibus imperdiet mauris.

Aliquam erat volutpat. Morbi sit amet neque tincidunt, efficitur eros tristique, gravida ipsum. Nam eget lacus non sapien accumsan aliquam. Nulla sit amet imperdiet nisl. Quisque lacinia ipsum semper nisl luctus, sit amet viverra tortor consectetur. Morbi ut leo sed eros egestas posuere. Donec id nisl sodales ante posuere congue. Vestibulum ut massa ante. Donec imperdiet neque vitae auctor ultrices. Nam ultricies, turpis nec vestibulum rhoncus, augue urna facilisis augue, id maximus nisi libero non nisi. Sed malesuada tristique sapien blandit ornare.

Phasellus pharetra ante ex, a hendrerit felis feugiat feugiat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla at varius purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla congue, lacus eget efficitur pharetra, nibh quam dignissim enim, a faucibus turpis nisl non eros. Nulla tellus nisi, vestibulum eget vehicula ut, placerat tincidunt elit. Nulla nec leo quis purus blandit sagittis.

Duis aliquam luctus ex, vitae pulvinar ante ultrices non. Sed sit amet lacus congue, viverra risus vel, pharetra leo. Maecenas nisi magna, pellentesque id eros nec, facilisis ultricies felis. In pulvinar nisl ipsum. Aenean quis cursus augue. Ut diam nisl, pretium nec interdum sed, dignissim eu libero. Aenean lobortis lectus efficitur mauris tincidunt, laoreet feugiat est convallis. Vivamus lacus enim, lobortis lobortis ipsum in, faucibus eleifend quam. Cras pellentesque ante sit amet justo ornare, in dictum sem gravida. Ut fringilla quis est non lacinia.

In hac habitasse platea dictumst. Nulla a auctor felis, vel elementum tortor. Ut varius leo odio, a dignissim ipsum tincidunt ut. Nulla tellus nulla, dapibus vitae semper non, ultrices vel ex. Nulla vehicula magna dui, sed malesuada leo dictum feugiat. Duis nunc risus, fermentum ut turpis varius, tempus rhoncus sem. Ut vel libero imperdiet, egestas felis a, ultricies leo. Maecenas mauris est, aliquet non urna et, dignissim sollicitudin nisi. Aenean condimentum, nisi et sagittis malesuada, mauris urna rutrum risus, a pulvinar lacus orci id ipsum. Ut varius congue leo, et tempor mauris mattis non. Suspendisse ac sapien in turpis commodo egestas nec ac nibh. Donec ac finibus nibh. Morbi ac urna sit amet lorem porttitor faucibus ultrices nec ligula.

Nulla varius magna in augue pellentesque elementum. Nullam ornare augue eget mi dignissim, ac feugiat orci pellentesque. Vestibulum urna enim, laoreet eget est vel, euismod tincidunt sapien. Integer in lectus et turpis scelerisque varius. Etiam lobortis dictum augue, sed efficitur mauris elementum eu. Cras sed turpis in lorem consectetur cursus varius non massa. Ut rhoncus, elit facilisis aliquam dapibus, mi nunc rhoncus diam, vitae pretium erat lacus quis leo. Aenean dictum nulla sit amet quam maximus condimentum. Nulla facilisi. Maecenas ut hendrerit eros, vitae maximus nibh. Cras laoreet magna est, ac eleifend nulla hendrerit et. Sed ullamcorper ut tellus eu consequat.

Sed eu erat sodales, pulvinar orci eu, congue turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec maximus vel risus in lacinia. Cras purus felis, sollicitudin ut magna nec, dictum dapibus mi. Cras pellentesque tellus non mi vestibulum, sed iaculis velit vehicula. Pellentesque rhoncus sollicitudin egestas. Aliquam convallis, nibh ac ultrices accumsan, nulla massa molestie mi, non dignissim leo nibh id arcu. Sed tempor luctus imperdiet. Ut ut pretium erat. Ut id nulla nibh. Morbi lacinia orci sem, a semper urna venenatis ac. Vivamus sed sem magna. Pellentesque auctor dignissim tristique. Mauris eu magna nunc. Nulla facilisi. Suspendisse pellentesque, elit ac fringilla dignissim, ex massa mollis ligula, rutrum tempor justo quam at dolor.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam odio lectus, convallis in tortor eu, dapibus porttitor purus. Vivamus sodales, urna vitae dictum ornare, neque massa suscipit nisl, a lobortis leo enim at dui. Sed vel felis pellentesque, pretium libero in, facilisis tellus. Vestibulum diam mauris, tristique porttitor nibh ut, fringilla finibus elit. Nulla hendrerit arcu ac mauris sagittis, at suscipit quam consequat. Donec viverra odio quis diam mollis, eget fermentum quam mattis. Donec accumsan sodales dui, a feugiat ipsum. Praesent ultricies tempor consectetur. Phasellus sed neque dolor. Morbi molestie suscipit magna, non malesuada elit lacinia ac. Aliquam erat volutpat. Quisque a felis viverra, pulvinar quam nec, molestie justo. Phasellus vel metus mattis, sodales nisi laoreet, semper libero. Aliquam erat volutpat. Morbi ornare, ante sit amet varius sagittis, turpis tellus dapibus nulla, fermentum scelerisque nibh leo quis diam.

Sed faucibus lectus dolor, ac fermentum augue fringilla sit amet. Praesent interdum ultricies nulla in condimentum. Etiam commodo sit amet arcu eget placerat. Praesent quis ante vel neque maximus hendrerit. Suspendisse neque metus, fermentum imperdiet magna scelerisque, dapibus finibus purus. Proin lacinia nisi eget urna tristique, ut aliquet tellus malesuada. Proin pellentesque mi eu nibh facilisis, sed feugiat neque lacinia. Sed ac tincidunt lorem, ac ultrices est. Sed in ex eu ipsum vestibulum suscipit. Nullam laoreet id nibh ac suscipit. Nulla facilisi. Maecenas convallis in mauris sit amet consequat.

Cras laoreet cursus tempus. Maecenas ac arcu lacus. Aenean sollicitudin eleifend ligula, sed euismod orci pharetra eget. Morbi eget aliquam massa. Fusce id egestas eros, non facilisis elit. Integer consequat et sapien eget pharetra. Fusce ut auctor mauris. Maecenas laoreet ultricies ligula, nec hendrerit ipsum semper quis. Quisque vitae orci id quam lacinia cursus ut in magna.

Suspendisse at nunc gravida, mollis nibh ut, faucibus eros. Vivamus non ante viverra, dapibus augue vel, aliquet risus. Praesent porta magna eu nisl lacinia ornare. Vivamus eleifend vestibulum ultrices. Nullam non quam ac massa porta porttitor. Vivamus tristique orci ligula. Aenean nisi tellus, commodo non elit vel, aliquet facilisis est.

Fusce consequat varius tellus, sed tempor felis interdum sit amet. Phasellus egestas purus vel enim fringilla iaculis. Suspendisse fringilla lorem ac leo iaculis venenatis. Ut sit amet aliquam ligula, vel tempor arcu. Etiam finibus, lorem eu consectetur maximus, leo metus efficitur enim, at aliquam velit odio sit amet felis. Nunc varius justo vel elit tincidunt convallis. Fusce ac ante eu enim ultrices rutrum in vitae libero. Nulla facilisi. Nullam in pretium erat. Nam mauris elit, commodo ut volutpat nec, bibendum placerat purus. Sed mollis at ex a consequat. Sed malesuada nunc eget ligula sagittis, molestie molestie metus sollicitudin. Quisque quam tellus, tincidunt eu nibh in, porta blandit augue. Curabitur vulputate, erat in consectetur viverra, lorem ipsum fringilla lorem, non feugiat orci odio eget justo.

Aenean auctor auctor nulla sit amet tempus. Sed non sem arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras erat ex, rutrum ac laoreet sed, gravida sit amet quam. Donec eu varius elit. Phasellus tincidunt ante vitae congue lobortis. Maecenas mollis ornare velit varius viverra. Sed elit dolor, placerat vitae ipsum in, tincidunt volutpat tellus. Duis suscipit ex at est mattis euismod. In ultrices sapien nec ipsum condimentum rutrum eget nec lorem. Sed suscipit nisl commodo justo vehicula pellentesque. Aenean ac sapien vel lorem pulvinar tincidunt eget non metus. Fusce eleifend, odio vel semper laoreet, risus massa egestas leo, ut porttitor nisi nisl quis mauris. Etiam pharetra nibh quis ipsum mattis rutrum.

Vivamus quis molestie velit. Duis aliquet risus arcu, id placerat velit commodo a. Nullam id elit faucibus, posuere dolor vitae, pellentesque nulla. Cras consectetur diam ut varius blandit. Quisque ullamcorper lorem mauris, id mollis risus luctus eu. Donec pellentesque tortor vitae lectus mollis commodo. Aliquam elementum ex urna, vel lacinia ipsum molestie sed. Vestibulum consectetur lorem ligula, in finibus tortor imperdiet a. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Praesent sit amet euismod nulla. Curabitur sit amet augue luctus, euismod massa ut, congue sapien. Ut metus orci, interdum sit amet elit eget, finibus pharetra nulla. Nullam aliquam ipsum sit amet ipsum laoreet tincidunt. Quisque congue efficitur purus in rhoncus. Donec nec nibh at ligula lobortis convallis. Maecenas viverra vitae diam eget rutrum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi purus velit, lobortis vel pretium ut, efficitur id justo. Nam aliquam interdum lacus, ac vulputate tortor auctor a. Aenean at consectetur sapien, sit amet ultricies nibh. Maecenas placerat nisi ac nunc rutrum bibendum id et nibh.

Phasellus imperdiet ante eget dui porttitor, vel commodo libero hendrerit. Sed eros lacus, auctor a egestas in, tincidunt vel purus. Duis dolor magna, lobortis non nulla nec, lacinia porttitor libero. Etiam porttitor porttitor eros. Vivamus ut cursus dolor, et consequat mi. Nullam sagittis vehicula nisl id dapibus. Aliquam ullamcorper a massa at bibendum. Sed ut convallis ligula. Nulla interdum faucibus mauris, non auctor lacus scelerisque sed. Ut ornare neque sed arcu porta consequat. Aenean quis maximus diam, ac cursus neque. Nunc eros arcu, volutpat gravida lacinia id, pretium eget ex. Vivamus finibus. **/